/// Flutter icons CustomIcons
/// Copyright (C) 2021 by original authors @ fluttericon.com, fontello.com
/// This font was generated by FlutterIcon.com, which is derived from Fontello.
///
/// To use this font, place it in your fonts/ directory and include the
/// following in your pubspec.yaml
///
/// flutter:
///   fonts:
///    - family:  CustomIcons
///      fonts:
///       - asset: fonts/CustomIcons.ttf
///
/// 
/// * RPG Awesome, Copyright (c) 2014, Daniela Howe
///         Author:    Daniela Howe & Ivan Montiel
///         License:   SIL (http://scripts.sil.org/OFL)
///         Homepage:  http://nagoshiashumari.github.io/Rpg-Awesome/
/// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
///         Author:    Dave Gandy
///         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
///         Homepage:  http://fortawesome.github.com/Font-Awesome/
///
import 'package:flutter/widgets.dart';

class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData ankh = IconData(0xe908, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aquarius = IconData(0xe90b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData archer = IconData(0xe90d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData aries = IconData(0xe910, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData beer = IconData(0xe92a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broadsword = IconData(0xe946, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData broken_skull = IconData(0xe94b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData cancer = IconData(0xe956, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData candle_fire = IconData(0xe957, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData capricorn = IconData(0xe95b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData croc_sword = IconData(0xe977, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossbow = IconData(0xe978, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_axes = IconData(0xe979, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData crossed_swords = IconData(0xe97d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dragon = IconData(0xe9a2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData droplet = IconData(0xe9a9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData emerald = IconData(0xe9af, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData eyeball = IconData(0xe9b5, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData fairy_wand = IconData(0xe9b6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData flame_symbol = IconData(0xe9c7, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gear_hammer = IconData(0xe9db, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gem_pendant = IconData(0xe9df, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gem = IconData(0xe9e0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gemini = IconData(0xe9e1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData gold_bar = IconData(0xe9e4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData grenade = IconData(0xe9e8, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData honeycomb = IconData(0xea02, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData hospital_cross = IconData(0xea07, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData knight_helmet = IconData(0xea1a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData kunai = IconData(0xea1b, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData large_hammer = IconData(0xea1d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData leo = IconData(0xea22, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData libra = IconData(0xea2a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData lightning_bolt = IconData(0xea2d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mass_driver = IconData(0xea39, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData mp5 = IconData(0xea46, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData musket = IconData(0xea49, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData pisces = IconData(0xea64, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData plain_dagger = IconData(0xea65, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData relic_blade = IconData(0xea7e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData revolver = IconData(0xea81, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData robot_arm = IconData(0xea85, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sagittarius = IconData(0xea8a, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scorpio = IconData(0xea8e, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData scroll_unfurled = IconData(0xea8f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData sickle = IconData(0xea9d, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData skull = IconData(0xeaa1, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData small_fire = IconData(0xeaa3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData speech_bubble = IconData(0xeaad, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData taurus = IconData(0xeac6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData thorny_vine = IconData(0xeacb, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData toast = IconData(0xeace, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData tower = IconData(0xead2, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData triforce = IconData(0xead6, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData vest = IconData(0xeae0, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData virgo = IconData(0xeae3, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData water_drop = IconData(0xeae4, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData wooden_sign = IconData(0xeae9, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData x_mark = IconData(0xeaec, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice = IconData(0xf522, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData dice_d20 = IconData(0xf6cf, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}

const getIcons = <String, IconData> {
  "ankh": CustomIcons.ankh,
  "aquarius": CustomIcons.aquarius,
  "archer": CustomIcons.archer,
  'aries': CustomIcons.aries,
  "beer": CustomIcons.beer,
  "broadsword": CustomIcons.broadsword,
  "broken_skull": CustomIcons.broken_skull,
  "cancer": CustomIcons.cancer,
  "candle_fire": CustomIcons.candle_fire,
  "capricorn": CustomIcons.capricorn,
  "croc_sword": CustomIcons.croc_sword,
  "crossbow": CustomIcons.crossbow,
  "crossed_axes": CustomIcons.crossed_axes,
  "crossed_swords": CustomIcons.crossed_swords,
  "dragon": CustomIcons.dragon,
  "droplet": CustomIcons.droplet,
  "emerald": CustomIcons.emerald,
  "eyeball": CustomIcons.eyeball,
  "fairy_wand": CustomIcons.fairy_wand,
  "flame_symbol": CustomIcons.flame_symbol,
  "gear_hammer": CustomIcons.gear_hammer,
  "gem_pendant": CustomIcons.gem_pendant,
  "gem": CustomIcons.gem,
  "gemini": CustomIcons.gemini,
  "gold_bar": CustomIcons.gold_bar,
  "grenade": CustomIcons.grenade,
  "honeycomb": CustomIcons.honeycomb,
  "hospital_cross": CustomIcons.hospital_cross,
  "knight_helmet": CustomIcons.knight_helmet,
  "kunai": CustomIcons.kunai,
  "large_hammer": CustomIcons.large_hammer,
  "leo": CustomIcons.leo,
  "libra": CustomIcons.libra,
  "lightning_bolt": CustomIcons.lightning_bolt,
  "mass_driver": CustomIcons.mass_driver,
  "mp5": CustomIcons.mp5,
  "musket": CustomIcons.musket,
  "pisces": CustomIcons.pisces,
  "plain_dagger": CustomIcons.plain_dagger,
  "relic_blade": CustomIcons.relic_blade,
  "revolver": CustomIcons.revolver,
  "robot_arm": CustomIcons.robot_arm,
  "sagittarius": CustomIcons.sagittarius,
  "scorpio": CustomIcons.scorpio,
  "scroll_unfurled": CustomIcons.scroll_unfurled,
  "sickle": CustomIcons.sickle,
  "skull": CustomIcons.skull,
  "small_fire": CustomIcons.small_fire,
  "speech_bubble": CustomIcons.speech_bubble,
  "taurus": CustomIcons.taurus,
  "thorny_vine": CustomIcons.thorny_vine,
  "toast": CustomIcons.toast,
  "tower": CustomIcons.tower,
  "triforce": CustomIcons.triforce,
  "vest": CustomIcons.vest,
  "virgo": CustomIcons.virgo,
  "water_drop": CustomIcons.water_drop,
  "wooden_sign": CustomIcons.wooden_sign,
  "x_mark": CustomIcons.x_mark,
  "dice": CustomIcons.dice,
  "dice_d20": CustomIcons.dice_d20
};